#
# Region definitions.
# - full_name and city_name are for readability/booktracking purpose only
# - different radius can be used for different search_city. In this case
#   radius should an array with the same length as search_city
#
# Usage：
# - ·search_city` will be ignored if `search_region` is specified.
# - under the hood search_city is replaced by `search_city` of the regions
#

[marketplace.facebook]
search_city = "windsor"
radius = 100

[item.iphone13]
search_phrases = "iPhone 13"
keywords = "(iphone) AND (13)"
min_price = 100
max_price = 200

[item.iphone13pro]
search_phrases = "iPhone 13 Pro"
keywords = "(iphone) AND (13) AND (pro)"
min_price = 150
max_price = 250

[item.iphone13promax]
search_phrases = "iPhone 13 Pro Max"
keywords = "(iphone) AND (13) AND (pro) AND (max)"
min_price = 200
max_price = 275

[item.iphone14]
search_phrases = "iPhone 14"
keywords = "(iphone) AND (14)"
min_price = 225
max_price = 280

[item.iphone14pro]
search_phrases = "iPhone 14 Pro"
keywords = "(iphone) AND (14) AND (pro)"
min_price = 225
max_price = 300

[item.iphone14promax]
search_phrases = "iPhone 14 Pro Max"
keywords = "(iphone) AND (14) AND (pro) AND (max)"
min_price = 250
max_price = 350

[item.iphone15]
search_phrases = "iPhone 15"
keywords = "(iphone) AND (15)"
min_price = 200
max_price = 380

[item.iphone15plus]
search_phrases = "iPhone 15 Plus"
keywords = "(iphone) AND (15) AND (plus)"
min_price = 200
max_price = 400

[item.iphone15pro]
search_phrases = "iPhone 15 Pro"
keywords = "(iphone) AND (15) AND (pro)"
min_price = 200
max_price = 430

[item.iphone15promax]
search_phrases = "iPhone 15 Pro Max"
keywords = "(iphone) AND (15) AND (pro) AND (max)"
min_price = 200
max_price = 500

[item.s23]
search_phrases = "Samsung S23"
keywords = "(samsung OR galaxy) AND (s23)"
min_price = 100
max_price = 180

[item.s24]
search_phrases = "Samsung S24"
keywords = "(samsung OR galaxy) AND (s24)"
min_price = 200
max_price = 300

[item.s25]
search_phrases = "Samsung S25"
keywords = "(samsung OR galaxy) AND (s25)"
min_price = 250
max_price = 450

[user.me]
notify_with = []
